SELECT
    product_id,
    sku,
    product_name,
    short_description,
    description,
    price,
    list_price,
    original_price,
    discount,
    discount_rate,
    rating_average,
    review_count,
    all_time_quantity_sold,
    quantity_sold,
    seller_id,
    seller_name,
    brand_id,
    brand_name,
    type,
    inventory_status,
    url_key,
    url_path,
    extracted_at_ts AS last_seen_at,
    dt
FROM {{ ref('stg_tiki_product_details') }}
